version: 2
checkout:
  post: 
    - git submodule update --init --recursive
dependencies:
  post:
    - gem install bundler
    - bundle install
jobs:
  build:

    # Specify the Xcode version to use
    macos:
      xcode: "9.0"
    shell: /bin/bash --login -eo pipefail

    steps:
      # Build the app and run tests
      - run:
          name: iOS Tests
          command: bundle exec rake test:ios
      - run:
          name: MacOS Tests
          command: bundle exec rake test:macos
      - run:
          name: CodeCov.sh
          command: bash <(curl -s https://codecov.io/bash)
      - run:
          name: Test Deployment
          command: |
            xcrun simctl create "Apple TV 1080p" com.apple.CoreSimulator.SimDeviceType.Apple-TV-1080p com.apple.CoreSimulator.SimRuntime.tvOS-11-2
            bundle exec rake test:deployment
            ./Scripts/jazzy.sh
